---
title: "discover outlier for template data"
author: "Sascha Siegmund"
date: "`r Sys.Date()`"
output: 
  github_document:
    fig_width: 10
    fig_height: 7
---

```{r, echo = FALSE}
knitr::opts_chunk$set(
  fig.path = "nb_figs/outlier_",
  warning = FALSE,
  message = FALSE
)
```



## purpose of notebook

  - [ ] 
  
## insights 

  - 


## load packages

```{r load packages, setup, message=FALSE}
library(tidyverse) # tidy data frame
library(plotly) # make ggplots interactive
```


## import data

```{r, message=FALSE}
df <- read_csv('../data/house_prices_regression/train.csv')
```


## overview

```{r}
head(df)
```
```{r}
summary(df)
```


## HDoutliers


```{r}
name = c('')
tmp_df <- df %>% select(MSSubClass, GarageArea, LotArea, SalePrice, GrLivArea) %>% na.omit()

library(HDoutliers)

outliers <- HDoutliers(tmp_df) # value = the indexes of the observations determined to be outliers
head(outliers)
plotHDoutliers(tmp_df, outliers) # If the data has more than two dimensions, it is plotted onto the principal components of the data that remains after removing outliers
```



## emstreeR 


```{r}
name = c('')
tmp_df <- df %>% rename(x = LotArea, y = SalePrice) %>% select(x, y)

library(emstreeR)

emst <- ComputeMST(tmp_df, scale = FALSE)
head(emst)

fig <- emst %>% 
  ggplot(aes(x = x, y = y, from = from, to = to)) +
    geom_point(alpha = 0.5) +
    stat_MST(color = 'red', linetype = 1, alpha = 0.5) +
    theme_minimal()
              
ggplotly(fig)
```



## outlier validation

- take appropriate viz from notebook describe_group and describe_one, describe_two

```{r}
name = c('')
tmp_df <- df %>% select(MSSubClass, GarageArea, LotArea, SalePrice, GrLivArea) %>%
  select_if(is.numeric) %>% na.omit()


outlier <- outliers::scores(tmp_df)
outlier <- outlier > 3 | outlier < -3 # more than 3 std away from mean is outlier
outlier <- outlier %>% as_tibble %>% mutate(outlier = rowMeans(.) > 0.2) # mark outliers for multiple columns
tmp_df <- bind_cols(tmp_df, outlier = outlier$outlier) %>% mutate(outlier = as.factor(outlier))

# https://r-charts.com/ranking/parallel-coordinates-ggplot2/
parcoord_plot <- GGally::ggparcoord(tmp_df,
           columns = 1:(ncol(tmp_df)-1), groupColumn = ncol(tmp_df),
           scale='center', # scaling: standardize and center variables
           showPoints = FALSE,
           # order = 'Outlying', # Ordering methods
           title = name,
           alphaLines = 0.1) +
      scale_color_manual(values = c("black", "red")) +
      theme_minimal() 
parcoord_plot <- ggplotly(parcoord_plot) %>% layout(autosize=T)

parcoord_plot
```







