---
title: "discover correlation in customer personality analysis data"
author: "Sascha Siegmund"
date: "`r Sys.Date()`"
output: 
  github_document:
    fig_width: 10
    fig_height: 7
---

```{r, echo = FALSE}
knitr::opts_chunk$set(
  fig.path = "nb_figs/corr_",
  warning = FALSE,
  message = FALSE
)
```



## purpose of notebook

  - [ ] 
  
## insights 

  - 


## load packages
  
```{r, setup, message=FALSE}
library(tidyverse) # tidy data frame
library(ggthemes) # for extra plot themes
library(plotly) # make ggplots interactive

# individual libraries are in the according cell
```


## import data

```{r, message=FALSE}
df <- read_csv('../data/heart_attack_classification/heart.csv')
```


## overview

```{r}
head(df)
```
```{r}
summary(df)
```


## correlation plot

-

```{r}
name = c('')
tmp_df <- df %>% select(-output) %>% 
  na.omit()

cor <- cor(tmp_df)
cor_mtest <- corrplot::cor.mtest(tmp_df, conf.level = 0.99) # combining correlogram with significance test
corrplot::corrplot(cor, method = "number", order = 'hclust', addrect = 3, p.mat = cor_mtest$p, insig = "pch") 

corrplot::corrplot(cor, p.mat = cor_mtest$p, low = cor_mtest$lowCI, upp = cor_mtest$uppCI, 
                   order = 'hclust', sig.level = 0.01, tl.pos = 'd', addrect = 3, rect.col = 'navy', 
                   plotC = 'rect', cl.pos = 'n', insig = "p-value")
```


## parallel coordinate plot

-

```{r}
name = c('')
tmp_df <- df %>% select(output, everything()) %>% 
  mutate(output = factor(output)) %>% 
  na.omit() 

# https://r-charts.com/ranking/parallel-coordinates-ggplot2/
parcoord_plot <- GGally::ggparcoord(tmp_df,
           columns = 2:ncol(tmp_df), groupColumn = 1,
           scale='center', # scaling: center, std, robust, 
           showPoints = FALSE,
           order = 'allClass', # scagnostics available
           title = name,
           alphaLines = 0.2) +
  theme_minimal() 
parcoord_plot <- ggplotly(parcoord_plot) %>% layout(autosize=T)

parcoord_plot
```
```{r}
name = c('')
tmp_df <- df %>% select(everything()) %>% 
  na.omit()


outlier <- outliers::scores(tmp_df)
outlier <- outlier > 3 | outlier < -3 # more than 3 std away from mean is outlier
outlier <- outlier %>% as_tibble %>% mutate(outlier = rowMeans(.) > 0.2)
tmp_df <- bind_cols(tmp_df, outlier = outlier$outlier) %>% mutate(outlier = as.factor(outlier))

# https://r-charts.com/ranking/parallel-coordinates-ggplot2/
parcoord_plot <- GGally::ggparcoord(tmp_df,
           columns = 1:(ncol(tmp_df)-1), groupColumn = ncol(tmp_df),
           scale='center', # scaling: standardize and center variables
           showPoints = FALSE,
           # order = 'Outlying', # Ordering methods
           title = name,
           alphaLines = 0.1) +
      scale_color_manual(values = c("black", "red")) +
      theme_minimal() 
parcoord_plot <- ggplotly(parcoord_plot) %>% layout(autosize=T)

parcoord_plot
```
```{r}
name = c('age', 'output')
tmp_df <- df %>% rename(x = name[1], y = name[2]) %>% select(x, y) %>% na.omit


tmp_df <- as_tibble(scale(tmp_df)) # scaling data required to align parcoord and other plots

outlier <- outliers::scores(tmp_df)
outlier <- outlier > 3 | outlier < -3 # more than 3 std away from mean is outlier
outlier <- outlier %>% as_tibble %>% mutate(outlier = x | y)
tmp_df <- bind_cols(tmp_df, outlier = outlier$outlier) %>% mutate(outlier = as.factor(outlier))

# https://r-charts.com/ranking/parallel-coordinates-ggplot2/
p1 <- GGally::ggparcoord(tmp_df,
           columns = 1:(ncol(tmp_df)-1), groupColumn = ncol(tmp_df),
           scale='globalminmax', # data already scaled
           showPoints = FALSE,
           splineFactor = TRUE,
           alphaLines = 0.1) +
    scale_color_manual(values = c("black", "red")) +
    theme_minimal() +
    ggtitle(paste("correlation of", name[1], "and", name[2], sep=" "))
p1 <- ggplotly(p1) %>% layout(yaxis = list(title = ''), xaxis = list(title = '')) %>%
  add_annotations(text = name[1], align = 'left', yref='paper', yref = 'paper', x = 1, y = 0, showarrow=FALSE) %>%
  add_annotations(text = name[2], align = 'left', yref='paper', yref = 'paper', x = 2, y = 0, showarrow=FALSE)

p2 <- tmp_df %>%
  ggplot(aes(x = y)) +
    stat_density(geom="line", trim = TRUE) + 
    scale_x_continuous(limits = c(min(tmp_df$x, tmp_df$y), max(tmp_df$x, tmp_df$y))) +
    coord_flip() +
    theme_minimal()
p2 <- ggplotly(p2) %>% layout(yaxis = list(showticklabels = FALSE, showgrid = FALSE, title = ''), 
                              xaxis = list(showticklabels = FALSE, showgrid = FALSE, title = ''))

p3 <- tmp_df %>%
  ggplot(aes(x = 1, y = y)) +
    geom_boxplot() +
    theme_minimal() 
p3 <- ggplotly(p3) %>% layout(yaxis = list(showticklabels = FALSE, showgrid = FALSE, title = ''), 
                              xaxis = list(showticklabels = FALSE, showgrid = FALSE, title = ''))

p4 <- tmp_df %>%
  ggplot(aes(x = x)) +
    stat_density(geom="line", trim = TRUE) + 
    scale_x_continuous(limits = c(min(tmp_df$x, tmp_df$y), max(tmp_df$x, tmp_df$y))) +
    coord_flip() +
    theme_minimal()
p4 <- ggplotly(p4) %>% layout(yaxis = list(showticklabels = TRUE, showgrid = TRUE, title = ''),
                              xaxis = list(showticklabels = FALSE, showgrid = FALSE, title = '', 
                                           autorange = "reversed"))

p5 <- tmp_df %>%
  ggplot(aes(x = 1, y = x)) +
    geom_boxplot() +
    theme_minimal() 
p5 <- ggplotly(p5) %>% layout(yaxis = list(showticklabels = FALSE, showgrid = FALSE, title = ''), 
                              xaxis = list(showticklabels = FALSE, showgrid = FALSE, title = ''))

# merge figures into one plot, via subplots, https://plotly-r.com/arranging-views.html
fig <- subplot(p4, p5, p1, p3, p2,  
               margin = 0, widths = c(0.05, 0.02, 0.86, 0.02, 0.05), 
               shareX = TRUE, shareY = TRUE, titleX = TRUE, titleY = TRUE) %>% layout()

fig
```





